- name: Deploy WebApp to Kubernetes
  hosts: localhost
  tasks:
    - name: Apply Kubernetes Deployment
      command: kubectl apply -f ../k8s/deployment.yml

    - name: Apply Kubernetes Service
      command: kubectl apply -f ../k8s/service.yml
